import { UserProvider } from '@/context/users'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode;
}
import { cookies } from 'next/headers'; // Import cookies

export default async function RootLayout({ children }: RootLayoutProps) {
  const token = cookies().get('chatbot_session')?.value;

  let user = '';

  const response = await fetch(process.env.BASE_URL + '/api/users', {
    method: 'GET',
    headers: {
      'Authorization': `Bearer ${token}`
    },
  })

  if (response.status === 200) {
    const { username } = await response.json();
    user = username;
  }


  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider user={user}>
          {children}
        </UserProvider>
      </body>
    </html>
  )
}
